### ISSUE TITLE
Option to disable running doctests

### ISSUE THREAD

**Issue by Anders429** [sourcefrog/cargo-mutants#14]
Is there an option somewhere to disable running doctests? I am attempting to run this on a fairly large project with over 50 doctests, but it causes each mutant to take a long time to run. That, combined with a lot of mutations (over 300) makes for a long run-time.

For comparison, running normally takes ~15 seconds for each mutation, which ends up being about an hour and a half. However, if I modify my library's `Cargo.toml` to disable doctests (setting `doctests = false`), the time for each mutant reduces to about 1-1.5 seconds each. That ends up being only approximately 7.5 minutes, which is much more desirable, especially if I want to run this in CI.

Is there a way a flag can be added to disable doctests? Or perhaps one already exists? In general, my doctests tend to test things already covered in my unit tests, and serve more as examples in the documentation, so I don't think much is lost by excluding them.

**Comment by sourcefrog** [comment]
Hi, thanks for the feedback.

There is no option for this at the moment but it would definitely make sense to add. Perhaps it should just be done through a general way to pass options to `cargo test`, because there are others that could be useful too. 

Perhaps

    cargo mutants -- --all-targets

(does that actually disable doctests? It looks like it.)

**Comment by sourcefrog** [comment]
Basically the same as #15 .
