### ISSUE TITLE
Test fails in cargo-mutants (unmodified) but works outside it fine

### ISSUE THREAD

**Issue by xd009642** [sourcefrog/cargo-mutants#20]
Hi me again :sweat_smile:, I have the following test which works always outside cargo-mutants but failed in the unmutated baseline test on the final assert. The manifest dir stuff is all correct in the run as it works for other tests of a similar pattern. The only thing that stands out as unusual in this test is the modifying of the `CARGO_HOME` environment variable. I'm going to ignore it for now to see if I can get through to running mutants and if I can I'll look into it more afterwards. But just making this issue in case you can see anything that stands out initially.

```rust
#[test]
fn cargo_home_filtering() {
    let new_home =
        Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/data/HttptestAndReqwest/new_home");
    let previous = env::var("CARGO_HOME");

    let mut config = Config::default();
    config.test_timeout = Duration::from_secs(60);
    config.set_clean(false);
    let restore_dir = env::current_dir().unwrap();
    let test_dir = get_test_path("HttptestAndReqwest");
    env::set_current_dir(&test_dir).unwrap();
    config.manifest = test_dir;
    config.manifest.push("Cargo.toml");

    env::set_var("CARGO_HOME", new_home.display().to_string());
    let run = launch_tarpaulin(&config, &None);
    match previous {
        Ok(s) => env::set_var("CARGO_HOME", s),
        Err(_) => {
            let _ = Command::new("unset").args(&["CARGO_HOME"]).output();
        }
    }
    let (res, _) = run.unwrap();

    env::set_current_dir(restore_dir).unwrap();

    assert_eq!(res.iter().count(), 1);
}
```

Also repo link: https://github.com/xd009642/tarpaulin

**Comment by sourcefrog** [comment]
I don't understand what this line is doing: it seems to launch a subprocess that unsets `CARGO_HOME` in its own env, but that seems pointless...?

    let _ = Command::new("unset").args(&["CARGO_HOME"]).output();

Without reading all the code this looks like a complicated way to override env and cwd for a subprocess...? 

Could you just do that through options on [`Command`](https://doc.rust-lang.org/std/process/struct.Command.html)?

It is still interesting and maybe a bug in cargo-mutants though.

**Comment by xd009642** [comment]
I'm overriding it for the test process, inside my code I spawn `cargo` which relies on this. But my own code uses it as well and that's not spawned. If the person running the test has set their own `CARGO_HOME` it will revert back to the original value for the rest of the test cases, if they didn't it will unset the variable. Although looking at it I should be using `std::env::remove_var` instead

**Comment by xd009642** [comment]
I don't want to spawn tarpaulin as a process in the test because I want to get the main report type and do asserts on the struct instead of trying to infer it from the tarpaulin printout or report types.

**Comment by sourcefrog** [comment]
Can you get more info out of the assertion about what's going wrong?

**Comment by xd009642** [comment]
So the assertion is counting the number of files, included in coverage. The test sets `CARGO_HOME` to be in the example project directory (because one user was doing that for vendoring). And then if tarpaulin ignores anything in the source tree if it's in `CARGO_HOME` it will only see one file with results. Otherwise it will pick up all the dependency source as potentially coverable files, when I ran it it picked up 1740 files which is likely all the source code.

So it seems that `CARGO_HOME` was as I set it when I spawned `cargo build` but somehow ended up changing when I went to filter out the results. That's just my initial educated guess, I'll have a play around some point after my current mutants run is finished to add some more printouts for the variable etc to help debug it

**Comment by sourcefrog** [comment]
So the main things that cargo-mutants does relevant to this is here: https://github.com/sourcefrog/cargo-mutants/blob/f5830c9409e3739ebf20bd7fbd4d2e1e7618564c/src/lab.rs#L74-L83

and

https://github.com/sourcefrog/cargo-mutants/blob/f5830c9409e3739ebf20bd7fbd4d2e1e7618564c/src/lab.rs#L163-L189

and 

https://github.com/sourcefrog/cargo-mutants/blob/f5830c9409e3739ebf20bd7fbd4d2e1e7618564c/src/run.rs#L56-L72

We copy the tree, then run `cargo` inside it with its cwd set to that directory. I don't override `CARGO_HOME` or `CARGO_MANIFEST_PATH` so it should just be either inherited from your shell or set by Cargo. (I haven't looked them up yet?)

---

Oh, I think I see it:

    Path::new(env!("CARGO_MANIFEST_DIR")).join

The [`env!` macro](https://doc.rust-lang.org/std/macro.env.html) will expand to the build-time CARGO_MANIFEST_DIR. Probably this target does not need to be rebuilt in the baseline directory, so it still points to `~/src/cargo-tarpaulin` not `/tmp/...`.

I'd suggest something like this: 
 
* If you want to locate files relative to the source tree from tests, don't use `env!`: cargo tests always run from the source directory so you can just use a relative path. 

* But: this won't work if you change directory, but in any case changing directory is not likely to work well with multithreaded tests, so it's better avoided.

* So maybe `launch_tarpaulin` should take the directory as an arg, rather than in the implicit global variable of process-wide cwd. It can always set CARGO_HOME and the cwd for any subprocesses it starts.

* Personally I would make a copy of the working directory from the source tree and use that, rather than letting cargo mutate it, again so that tests are isolated from each other.

The cargo-mutants tests do both of these: https://github.com/sourcefrog/cargo-mutants/blob/f5830c9409e3739ebf20bd7fbd4d2e1e7618564c/tests/cli.rs#L188-L200

---

For cargo-mutants the most actionable thing is probably an option to not copy `/target`, which will flush out bugs like this but at the cost of making builds slower.

**Comment by xd009642** [comment]
First off thanks for this, insight into how cargo-mutants works is really interesting, and I imagine I've given you kinda a horrible issue given all the things my project does to work as a dev tool for other peoples weird project structures. I guess it feels nice to be on the other side of it for once :sweat_smile: 

> If you want to locate files relative to the source tree from tests, don't use env!: cargo tests always run from the source directory so you can just use a relative path.

~~Hmm I'm sure I've had problems with that before, but maybe it was workspace crates or an older rust :thinking:.~~ So I remember the problem with this, I don't run via `cargo test` instead I have to build test binaries and then attach to them by launching them explicitly. If you run a test binary not via cargo test the cwd is not set up as the source directory but rather the directory you run from. This has caused issues with tarpaulin in projects with workspaces but isn't relevant to tarpaulin's tests - but that'll be why I wrote it that way. I'll try to refactor it and see how that changes things tomorrow.

> But: this won't work if you change directory, but in any case changing directory is not likely to work well with multithreaded tests, so it's better avoided.

One of the reasons my tests are ran single-threaded

> So maybe launch_tarpaulin should take the directory as an arg, rather than in the implicit global variable of process-wide cwd. It can always set CARGO_HOME and the cwd for any subprocesses it starts.

I've had users complain about their global env vars in CI being overridden so I tend to prefer to keep as much of the users settings as possible and infer if anythings set in such a way it can mess up results. It seems to have worked pretty well so far because most people aren't doing anything too "out there". 

As for directory as an arg it is kinda an arg. I can pass in a list of config structs with the directory either explicitly specified or not specified. Then the method to access the cwd returns the right one which I then use, this makes it possible to run in a monorepo and aggregate all the results. But means that the cwd is changing for each project tarpaulin analyses.

**Comment by xd009642** [comment]
Just an update I ended up moving to `rusty-fork` and also changing `Command::new("unset").args(&["CARGO_HOME"])` to `env::remove_var("CARGO_HOME")` and the unmutated baseline passes

**Comment by sourcefrog** [comment]
Great! I'll leave open #22 and close this one then. Keep the reports and suggestions coming!
