### ISSUE TITLE
Adding as dev-dependency should be sufficient

### ISSUE THREAD

**Issue by barafael** [sourcefrog/cargo-mutants#30]
Currently, if I want to use `#[mutants(skip)]`, I need to add `mutants` to `Cargo.toml` as a `dependency`. The readme at least promises that there is no effect on the generated code by this. I think it should be sufficient to add it as a `dev-dependency`.

Minor issue, thanks for the tool!

**Comment by sourcefrog** [comment]
Hi! Interesting idea, but I don't think it will work:

`#[mutants(skip)]` markers into the main body of your code (in `lib/**.rs`), not into tests, because it's the non-test code that cargo-mutants would normally try to mutate. (All test code is already excluded from generating mutants.)

So `cargo build` (or `install` or `run`) needs to be able to find the `mutants` crate to apply that attribute.

According to <https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html>

> Dev-dependencies are not used when compiling a package for building, but are used for compiling tests, examples, and benchmarks.

So I think this would break regular builds...

**Comment by sourcefrog** [comment]
Yep, it does fail like that when I move it to a dev-dependency:

```
error[E0433]: failed to resolve: use of undeclared crate or module `mutants`
   --> src/index.rs:234:3
    |
234 | #[mutants::skip] // By default it returns "" which causes a loop. TODO: Avoid the loop.
    |   ^^^^^^^ use of undeclared crate or module `mutants`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `conserve` due to previous error
```

 I'll mention this in the doc.
