### ISSUE TITLE
mutating constants leads to false 'MISSED'

### ISSUE THREAD

**Issue by cehteh** [sourcefrog/cargo-mutants#316]
I have some code like:

```
const KB: usize = 1024;
const MB: usize = KB * 1024;
const GB: usize = MB * 1024;

struct AllocationStrategy {
    pub min_allocation: usize,
    pub grow_half: usize,
    pub grow_const: usize,
}

const DEFAULT_ALLOCATION_STRATEGY: AllocationStrategy = AllocationStrategy {
    min_allocation: 32,
    grow_half: 8 * MB,
    grow_const:  1 * GB,
};
```

cargo-mutants happily mutates these constant operations "replace * with /". These are constants and never meant to be 'wrong' and thus not really tested. Of course I could either tests or `#[mutants:skip]` those. But I would argue that mutants shouldn't mutate operations with constants. Whats your opinion on this?

**Comment by cehteh** [comment]
Another observation: 

Adding `#[mutants:skip]` to the const definitions doesn't make cargo-mutants skip them. I had to write a `#[test]` to silence it.

**Comment by sourcefrog** [comment]
Hi, 

It would certainly be useful to let you put `#[mutants::skip]` on the const statement; I split out #318 specifically for that. Until that is fixed probably the best option is to skip it with a regex in `.cargo/mutants.toml`.

In your example code, I think cargo-mutants is actually flagging a real coverage gap that you should at least think about. If they can never be wrong then why are they e.g. 1GB rather than 1KB or 1PB or 0? Would it make any difference if you did have a real bug here and for example accidentally swapped two of the fields? 

The net effect of mutants replacing `+` with `/` here will I think be that `grow_half` and `grow_const` will be set to 0 (8/1024/1024 rounds to 0) in two different scenarios. This might mean that the allocations never grow? Maybe if the code is well tested it's surprising that no test fails if the allocation never grows? I can't see the rest of your code, but if I was writing an allocator with user-configurable parameters then I might want to test that the parameters, in connection with some allocation patterns, cause some expected effects.

Of course cargo-mutants is just suggesting things to think about not telling you what to do. If you decide that the numbers are really very arbitrary and any int would be just as good, or that the behavior of the allocation strategy is not very important to test, it's totally valid to skip it, but it's up to you.

**Comment by cehteh** [comment]
> Hi,
> 
> It would certainly be useful to let you put `#[mutants::skip]` on the const statement; I split out #318 specifically for that. Until that is fixed probably the best option is to skip it with a regex in `.cargo/mutants.toml`.

Thanks, for the time being I put a tests in the code:
    assert_eq!(MB, KB * 1024);
    assert_eq!(GB, MB * 1024);
    assert_eq!(DEFAULT_ALLOCATION_STRATEGY.grow_half, 8 * MB);
    assert_eq!(DEFAULT_ALLOCATION_STRATEGY.grow_const, 1 * GB);


> 
> In your example code, I think cargo-mutants is actually flagging a real coverage gap that you should at least think about. If they can never be wrong then why are they e.g. 1GB rather than 1KB or 1PB or 0? Would it make any difference if you did have a real bug here and for example accidentally swapped two of the fields?
> 
> The net effect of mutants replacing `+` with `/` here will I think be that `grow_half` and `grow_const` will be set to 0 (8/1024/1024 rounds to 0) in two different scenarios. This might mean that the allocations never grow? Maybe if the code is well tested it's surprising that no test fails if the allocation never grows? I can't see the rest of your code, but if I was writing an allocator with user-configurable parameters then I might want to test that the parameters, in connection with some allocation patterns, cause some expected effects.
> 
> Of course cargo-mutants is just suggesting things to think about not telling you what to do. If you decide that the numbers are really very arbitrary and any int would be just as good, or that the behavior of the allocation strategy is not very important to test, it's totally valid to skip it, but it's up to you.

Yep the thing is tested but in the less strict way that growing happens when necessary and be at least as much needed. Actual reallocation size / growing strategy is rather some side-effect that is not exposed.
