### ISSUE TITLE
Module file path incorrect when nested under `mod` block

### ISSUE THREAD

**Issue by danjl1100** [sourcefrog/cargo-mutants#327]
When I try to use `cargo-mutants` in my crate, it reports that some modules are not found.   It seems when a `mod` (no block) is defined within a `mod` block, the relative path is not fully tracked.

The description below is based on a [minimal reproduction](https://github.com/danjl1100/cargo-mutants-issue).

## Desired behavior

```
$ cargo mutants
Found 4 mutants to test
ok       Unmutated baseline in 0.2s build + 0.1s test
 INFO Auto-set test timeout to 20s
MISSED   src/toplevel/nested.rs:2:10: replace + with * in add in 0.2s build + 0.1s test
4 mutants tested in 1s: 1 missed, 3 caught
```

## Failure behavior

```
$ cargo mutants
 WARN referent of mod not found parent_path="src/lib.rs" mod_name=nested tried_paths=["/home/ned/git/cargo-mutants-testcase/src/nested.rs", "/home/ned/git/cargo-mutants-testcase/src/nested/mod.rs"]
Found 0 mutants to test
 WARN No mutants found under the active filters

$ cargo mutants --version
cargo-mutants 24.3.0
```

<details>
<summary>Details of the test case</summary>
Details of the change from "desired" to "failure" that triggers the issue

- `src/lib.rs`
    ```patch
    -pub mod toplevel;
    +pub mod toplevel {
    +    pub mod nested;
    +}

     #[cfg(test)]
     mod tests {
        use super::toplevel::nested::*;

        #[test]
        fn it_works() {
            let result = add(2, 2);
            assert_eq!(result, 4);
        }
    }
    ```
- `src/toplevel.rs` (deleted)
    ```patch
    -pub mod nested;
    ```
- `tree` summary
    ```patch
     $ tree .
     .
     ├── Cargo.lock
     ├── Cargo.toml
     └── src
         ├── lib.rs
    -    ├── toplevel.rs
         └── toplevel
             └── nested.rs
    ```
</details>

## Proposed solution

Looking over [DESIGN.md](https://github.com/sourcefrog/cargo-mutants/blob/main/DESIGN.md#discovering-mutants), I see that module discovery ignores `mod` statements with a block.

Would you be open to a PR to track the nesting of `mod` blocks, to calculate the path to `mod` files (with no block) similar to rustc?  I don't have much experience with the `syn` crate, but would be happy to see how this might work for `cargo-mutants`.

### Metadata
<details>
<summary>Tested using branch `main` at 442412650fc9770f3bc84467e1b104f5ef51b7a6</summary>

```
$ git clone https://github.com/sourcefrog/cargo-mutants.git

$ cd cargo-mutants

$ git rev-parse HEAD
442412650fc9770f3bc84467e1b104f5ef51b7a6

$ cargo build

$ ./target/debug/cargo-mutants mutants --version
cargo-mutants 24.3.0

[setup minimal reproduction case]
$ cd ../cargo-mutants-minimal-reproduction

$ ../cargo-mutants/target/debug/cargo-mutants mutants
```

</details>

**Comment by sourcefrog** [comment]
Thanks very much for the clear report and reproduction! I had not realized that you could have mod statements that correspond to multiple directories but it makes sense.

I think `visit_item_mod` should already be tracking the nested namespaces. https://github.com/sourcefrog/cargo-mutants/blob/442412650fc9770f3bc84467e1b104f5ef51b7a6/src/visit.rs#L341-L356

The problem is that the accumulated list of `external_mods` only takes the last component of the path. Maybe it should use the whole stack... although, we need to probably be careful to get this right if the mod we're already looking at is some layers down.

The interaction of the stack with the existing filenames suggests to me that maybe a better test is something with a mix of a file that is itself 2 levels down, and that then has an external mod that is then some further levels down.

A PR would be very welcome.

Some ideas on how to start:

- [ ] Copy your tree under testdata with an appropriate directory and package name
- [ ] Add it to the workspace exclusions in `/Cargo.toml`
- [ ] Add the namespaces to the stack in `visit.rs` 
- [ ] Add a test in `visit.rs` for reading the testdata, like in https://github.com/sourcefrog/cargo-mutants/blob/442412650fc9770f3bc84467e1b104f5ef51b7a6/src/visit.rs#L589-L599

**Comment by sourcefrog** [comment]
Also, not necessarily in the same PR: at the moment https://github.com/sourcefrog/cargo-mutants/blob/442412650fc9770f3bc84467e1b104f5ef51b7a6/src/visit.rs#L65-L74 only warns if it can't find a mod, but at least for tests we should probably have an option to make this an error.

https://github.com/sourcefrog/cargo-mutants/blob/442412650fc9770f3bc84467e1b104f5ef51b7a6/src/visit.rs#L457-L468
