### ISSUE TITLE
Add a command line argument to enable timeouts

### ISSUE THREAD

**Issue by AidanConnelly** [sourcefrog/cargo-mutants#7]
While there are issues with killing the test process while in progress, for some repositories this isn't an issue, and timeouts could be enabled by the command line

**Comment by sourcefrog** [comment]
Yes, this would be a good thing. I did previously have timeouts, but removed them because killing the direct child process (`cargo`) does not terminate the test binary grandchildren processes, which are the ones that are actually stuck.

However, the `subprocess` crate now has support for starting things in a pgroup, which should be enough to let us stop the whole lot at the timeout. I'm not sure about Windows yet.

**Comment by sourcefrog** [comment]
Note to self: with the child running in a different pgroup, we need to specially terminate it if the cargo-mutants process is interrupted.

**Comment by sourcefrog** [comment]
Design: https://github.com/sourcefrog/cargo-mutants/blob/timeout/DESIGN.md#handling-timeouts

**Comment by sourcefrog** [comment]
OK I think this is now working in https://github.com/sourcefrog/cargo-mutants/tree/timeout. I will add some more tests before merging, but please try it out and let me know.
