### ISSUE TITLE
Improving/refactoring test names and adding test naming convention

### ISSUE THREAD

**Issue by dmoka** [sourcefrog/cargo-mutants#74]
I believe that we could improve the names of our automated tests, and setting up a guideline for it, to
- make them more readable
- be able to capture more business/functional knowledge in the test names
- having them "standardized"

The `ShouldWhen` and the `GivenWhenThen` template are the most popular ones, personally I am a big fan of `ShouldWhen` template as it is quite flexible in most of the cases. But I am open to any other suggestions :)

Of course just as a guideline, and not a rigid rule. But eventually we could add this guideline to [CONTRIBUTING testing section](https://github.com/sourcefrog/cargo-mutants/blob/main/CONTRIBUTING.md#testing)

Just to pick some examples:
```
list_mutants_well_tested_exclude_folder_filter 
```
would become
```
exclude_option_should_exclude_folder_when_specified_with_slash
```

Or

```
copy_testdata_doesnt_include_build_artifacts
```

would become

```
build_artifcats_should_not_be_included_when_testdata_is_copied
```

Or 

```
error_when_no_mutants_found
```

would become

```
mutants_generation_should_return_error_when_no_mutants_are_found
```

What do you think?

**Comment by sourcefrog** [comment]
I think it's good to make test names quite self explanatory, and therefore they will often be much longer than non-test function names. Even more than non-test code, if it seems like it needs a comment it's worth first making the name more explicit. 

Quite possibly some of the existing names are too short as I've been increasingly come to feel this way about Rust this year.

I'm slightly against including "noise words" like "should", "when" and "given" just for the sake of a template because they use up more visual space than they are really semantically earning. `error_when` conveys as much information than `should_return_error_when` in half the space. The noise words make it harder to see the parts that vary. They're not "banned" but I am not sure it's useful to make a point of adding them. 

    list_mutants_well_tested_exclude_folder_filter 

So this one could be a bit longer, but it does have the advantage of including the command name `list-mutants` and the name of the tree (`well_tested`). I could go for something like `list_mutants_in_well_tested_tree_exclude_folder`.

    copy_testdata_doesnt_include_build_artifacts

This too includes the name of the thing it's testing, the function `copy_testdata`, so you can search for it. I think that's better than rewriting it to `when_testdata_is_copied`, also shorter. If read as an English sentence it seems pretty clear.

    error_when_no_mutants_found

Again this seems like a pretty clear though terse sentence (clause)? We could read them as assertions that something is true or something happens.

So overall:

* thanks for the suggestion, I appreciate the thought you put into it
* let's add something to CONTRIBUTING about making test names read like clear assertions when read aloud
* I'm not convinced about those formulas being more than suggestions for how to form sentences
* Let's fix any particular tests that have unclear names but maybe not necessarily rename everything

**Comment by dmoka** [comment]
Absolutely, Martin!

It definitely not a critical issue, and it might be that I am biased a bit as I really got used to such standardized namings. When I first started working on the repo, and reading the tests, I had some difficulties due to the lack of such a naming template, that was the trigger to open this issue...

Anyway, small thing, and I also agree with some of your points you have. Without such template, we can still produce readable test names. It also shows that software engineering is not black and white. :slightly_smiling_face:

**Comment by sourcefrog** [comment]
I added some advice on this in 8bc85a2.

Some existing tests might have unclear names and it would be fine to improve them along the lines discussed above if we're in the area. Bear in mind the Insta assertion files also probably need to be renamed.

I don't think this is worth keeping open as a bug in itself but I'm glad we talked about it.

**Comment by dmoka** [comment]
Great addition with the `test naming` guidance, like it!

agree, we can close this issue.
